[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
builtin_and_spl_cpi = "J3kSr6FzQLxVzkNHaq2YTddaGPy23E2kBcLKBHGP6oD9"
account_data_anchor_program_example = "EjVpuq1j4F8vXequaJEGYH8WMpKytdcv24i39say94uA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mobula-dev/lewis/soon-integration-test/program-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
