/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestERC20 } from "./TestERC20";
export * as factories from "./factories";
export { TestERC20__factory } from "./factories/TestERC20__factory";
